spring:
  application:
    name: lakeside-hotel
  datasource:
    url: jdbc:postgresql://localhost:5432/lakeside
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
